# Generated by Django 4.1.3 on 2022-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_dog_owner_customuser_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=12),
        ),
    ]
