# Generated by Django 4.1.3 on 2022-11-28 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_customuser_dog_remove_dog_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ManyToManyField(related_name='dog_breed', through='database.DogBreed', to='database.breed'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ManyToManyField(related_name='dog_user', through='database.DogUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
