# Generated by Django 4.1.3 on 2022-11-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_doguser_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doguser',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.dog'),
        ),
    ]
