# Generated by Django 4.1.3 on 2022-12-01 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_breed_max_height_female_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dimension', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='breed',
            name='max_height_female',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='max_height_male',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='max_weight_female',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='max_weight_male',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='min_height_female',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='min_height_male',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='min_weight_female',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='min_weight_male',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=23, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.activitylist')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.dog')),
            ],
        ),
    ]
