# Generated by Django 4.1.3 on 2022-12-01 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_activitylist_alter_breed_max_height_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='amount',
            field=models.TextField(max_length=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
