# Generated by Django 4.1.3 on 2022-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_activity_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='amount',
            field=models.TextField(max_length=15),
        ),
    ]
