# Generated by Django 4.1.3 on 2022-12-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-time']},
        ),
    ]
