# Generated by Django 4.1.3 on 2022-12-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylist',
            name='verb',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
