# Generated by Django 4.1.4 on 2022-12-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_weightchange_heightchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name']},
        ),
    ]
